### PR TITLE
Mention related projects

### PR DESCRIPTION
**Pull request by Bisaloo**

### CODE REVIEW

**Comment by Bisaloo** [comment]
Hi @aspina7 @nsbatra, as mentioned during the workshop, I'd love to get your feedback on this paragraph highlight the differences between sitrep and episoap.
I have a partial view of the question and I think your opinion as experts on sitrep would be very valuable.

**Comment by aspina7** [comment]
hi @Bisaloo thanks for reaching out as well as mentioning {sitrep} and sorry for the delayed reply. 
Just a couple points to add: 
- in line 61 could you please change "R4Epi" to "Applied Epi", we will be renaming before launch
- Could you perhaps also mention that we will be adding a generic template which is not disease/organisation specific please? 
- I realise this is unconventional, and the norm is to only mention other R packages, however I wonder if it might be relevant to mention the [epiRhandbook ](https://epirhandbook.com/en/)- as that provides alternative approaches to completing an analysis, and so might be related to the episoap project too? 

Would be interested to hear what other types of pipelines you plan on adding - perhaps worth organising a call to look at ways of synergising? One thing I have thought about is an interactive "report builder" that allows people to pull code snippets together, drag and drop style, that then gives them an rmd outline to workthrough.... 

happy to discuss add more input if helpful 
thx 
alex

**Comment by Bisaloo** [comment]
For the second part, it looks like you are proposing something similar to https://github.com/epiverse-trace/pitcher/issues/6. I agree it would be super useful, even beyond epi. It's a bit complex but I think I have a good general idea of how we could do this.

Happy to hear more thoughts on this specific topic there.

**Comment by aspina7** [comment]
thx hugo - I was thinking more for end-users that are producing reports/analyses rather than for developers, but yes similar conceptually

**Comment by aspina7** [comment]
Hi @Bisaloo just following up to say have you seen: 
https://github.com/epirecipes/epicookbook

**Pull request merged**
