### PR TITLE
Address {incidence2} grouped data not working with `EpiNow2::regional_epinow()`

### LINKED ISSUE #118: Errors with `regional_epinow`
When running `regional_epinow` in the transmissibility pipeline:

`res_epinow2_group <-  regional_epinow(dat_i_day,
    generation_time = generation_time,
    stan = stan_opts(samples = 1e3, chains = 2),
    rt = rt_opts(gp_on = "R0"),
    horizon = 0,
    CrIs = c(0.5, 0.95),
    return_output = TRUE,
    verbose = FALSE,
    logs = NULL
  ) `

The code runs but I'm getting a series of errors which result in the output not having any data for the different regions, here is an example for London, but the same error is generated for the remaining regions of the country:

_INFO [2024-01-09 13:03:58] Initialising estimates for: London
ERROR [2024-01-09 13:03:58] London: 'names' attribute [1] must be the same length as the vector [0] - <-, names(ids), paste(names(type_n), "id", sep = "_")
_INFO [2024-01-09 13:03:59] Completed regional estimates_
_INFO [2024-01-09 13:03:59] Regions with estimates: 0_
_INFO [2024-01-09 13:03:59] Runtime error in London : London: 'names' attribute [1] must be the same length as the vector [0] - <-, names(ids), paste(names(type_n), "id", sep = "_")_
_INFO [2024-01-09 13:03:59] Producing summary_
_INFO [2024-01-09 13:03:59] No summary directory specified so returning summary output_
_INFO [2024-01-09 13:03:59] Errors caught whilst generating summary statistics:_
_INFO [2024-01-09 13:03:59] Error in .checkTypos(e, names_x): Object 'variable' not found amongst_

@jamesmbaazam do you know what the problem could be? I'm sure it's easy to fix but I've been looking at the R file for `epinow` and I'm not sure at what point the error is happening

Thanks!

### PR DESCRIPTION
**Pull request by jamesmbaazam**
This PR attempts to address #118 but is not for merging into main as it's a branch of `Tx_pipeline_update`. 

In this PR, I suggest improvements to some terminology and provide a fix #118, where a grouped dataset created with {incidence2} does not work smoothly with `EpiNow2::regional_epinow()`. It appears in the grouped dataset, the date column is no longer valid for use with {EpiNow2}. I will investigate further why that is the case. 

@CarmenTamayo could you check out this branch and run it locally to see if it fixes the issue you raised? It works for me.

### CODE REVIEW

**Comment by CarmenTamayo** [comment]
hello @jamesmbaazam,
I tried the modification to add `dplyr::mutate(date = as.Date(date))` and it still didn't work properly
Then I realised the problem was that the column "count_var" from incidence2 was still in the dataset, which was generating an error, I deleted the column first and then the process worked.
I'm not going to merge this PR as I'm trying to solve another issue by which I'm not able to pull the changes from GitHub to my local version, but I've added the changes you suggested in this PR- I hope this is okay
Thank you James!

**Comment by CarmenTamayo** [comment]
Additionally, I was wondering why the change in terminology, i.e., from global to aggregated transmissibility? Is there a reason behind this suggestion other than personal preference? If so I think that global might be more intuitive as aggregated transmissibility might be misinterpreted or confused with other parts of the report where aggregated vs linelist data is used

**Comment by jamesmbaazam** [comment]
> hello @jamesmbaazam, I tried the modification to add `dplyr::mutate(date = as.Date(date))` and it still didn't work properly Then I realised the problem was that the column "count_variable" from incidence2 was still in the dataset, which was generating an error, I deleted the column first and then the process worked. 

That's interesting. I wonder how that was causing an error. It's good that you caught it.

> I'm not going to merge this PR as I'm trying to solve another issue by which I'm not able to pull the changes from GitHub to my local version, but I've added the changes you suggested in this PR- I hope this is okay Thank you James!

Yes, this wasn't necessarily for merging as stated in the PR description. You can simply close it with a comment.

**Comment by jamesmbaazam** [comment]
> Additionally, I was wondering why the change in terminology, i.e., from global to aggregated transmissibility? Is there a reason behind this suggestion other than personal preference? If so I think that global might be more intuitive as aggregated transmissibility might be misinterpreted or confused with other parts of the report where aggregated vs linelist data is used

That's fine. I'll leave that to you as it was only a suggestion. The term "global" could be confused with the geographic term. You could use something like "unstratified", which is clear by definition.

**Pull request closed without merging**
